using System;
using System.Runtime.InteropServices;
using static System.Console;

public static class Program
{
  public static void Main(string[] args)
  {
    string message = "Dotnet-bot: Welcome to using .NET Core!";

    if (args.Length > 0)
    {
      message = String.Join(" ", args);
    }

    WriteLine(GetBot(message));
    WriteLine("**Environment**");
    WriteLine($"Platform: .NET Core 2.0");
    WriteLine($"OS: {RuntimeInformation.OSDescription}");
    WriteLine($"Is Windows: {RuntimeInformation.IsOSPlatform(OSPlatform.Windows)}");
    WriteLine($"Is Linux  : {RuntimeInformation.IsOSPlatform(OSPlatform.Linux)}");
    WriteLine($"Is OSX    : {RuntimeInformation.IsOSPlatform(OSPlatform.OSX)}");
    WriteLine($"Environment OS: {Environment.OSVersion}");
    WriteLine();

    

    

  }

  public static string GetBot(string message)
  {
    string bot = $"\n        {message}";
    bot += @"
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .                           ......
            ..    .            ..        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....

";
    return bot;
  }
}
